#feign:
#    httpclient:
#        enabled: true
#    hystrix:
#        enabled: false  

hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: true
                isolation:
                    thread:
                        timeoutInMilliseconds: 120000

ribbon:
    ReadTimeout: 120000
    ConnectTimeout: 5000
        
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: ALWAYS

mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapperLocations: classpath:mapper/**/*.xml
    typeAliasesPackage: com.hgny.**.entity
    mapUnderscoreToCamelCase: true
    global-config:
        db-config:
            idType: 0
            fieldStrategy: NOT_NULL

eureka:
    instance:
        preferIpAddress: true

spring:
    application:
        config:
            path: classpath:rule.xml
    mvc:
        throw-exception-if-no-handler-found: true
    resources:
        add-mappings: false
    zipkin:
        base-url: http://localhost:9411
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/app_eemseeyes?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: manager
        #url: jdbc:mysql://172.22.1.249:3306/app_eeyes_schedule?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        #username: h_eems_web
        #password: Yweb201303
        druid:
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true
            