feign:
    httpclient:
        enabled: true
    hystrix:
        enabled: true

hystrix:
    threadpool:
        default:
            coreSize: 200
            maxQueueSize: 1000
            queueSizeRejectionThreshold: 800
    command:
        default:
            execution:
                timeout:
                    enabled: true
                isolation:
                    thread:
                        timeoutInMilliseconds: 120000

ribbon:
    ReadTimeout: 120000
    ConnectTimeout: 5000

eureka:
    instance:
        preferIpAddress: true
        metadataMap:
            group: eeyescloud-back-group
            version: 1.0

mybatis-plus:
#    configuration:
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapperLocations: classpath:mapper/**/*.xml
    typeAliasesPackage: com.hgny.cloud.back.**.entity
    mapUnderscoreToCamelCase: true
    db-config:
        idType: 0
        fieldStrategy: NOT_NULL

spring:
    servlet:
        multipart:
            max-file-size: 10MB
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    application:
        config:
            path: classpath:rule.xml
    mvc:
        throw-exception-if-no-handler-found: true
    resources:
        add-mappings: false
    zipkin:
        base-url: http://localhost:9411
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: "{cipher}AQC+1pqywla2Gk7r8U3BKkLseUWDcPHld9Og/Fwo9x8DhkAsGhzWWRt/OICRazQke0IK1NKBRNQ257fIpEXQKPMKAZrxbD7uVlzdyNb6U1wDNXR5FG7aOcYNiMdvY3avXgMvq61njuclQ0oJgMCcy4SKeGe0Oldde3Ydu7AFjJNKH7qj0VB6iNOxwI3/kGgPgFUyONrweR64jGVa50Kza0DHZyob/px6buw+Lw9AHSyeo3gCqy7exUh6xKaMEwFIm1LOuyptIxjxMwJ1T23pcEuNC/lUALEL4cuBubwLwWBrKSWDPJ7VmNVMZyuGWevzL07buCdmwSQ60E8W47f6ZjLJMu+ylPjh7Eis5MuEvt8Q3o8PdlUqFM3MS2mqcFpHHt5lr/MK9RyVIbxjB6S5AXBbTfVxs75DIBdqHaBF6IB2HRq5Tcg7MC+35u/ph3gqnFsctcG/m89fr/dQncIs2ytftDCMs/2LVf2jY2nBvcsWCOJz5gCzS+IIT9YqNlPHogk="
        username: "{cipher}AQCth04c9xQsPoEvFk6qkOJVffka4jRdXGacYq5c/twTFmpegniCOddE6Mj4lV9SLraYJk7jzFLJPyQp6fOLGwCg5jfx/5/RE85Ah4cmG8iQFBZRe3+huyyXRTa5p6ClLxZYvUxup3Z8y5PWRT0HZJbMexwqvvRyGTWCTDCAcKRNmSL29HjENUl7NT+a9FH3NZyz1Dk/iIHkwlK4LMuaSWaSfnXk2poeLZBgOPCVDncKmOf0aU2voH9XMhpmsnIEX+T937W9FyXLy9fc/A5UrvnGZqDfW0taS0dVE8TfeGPch0Kjb9J+M0/VQAW56tE2Xmvk3tBoOMXAgr56JnK6V1eH8566IWVDKyqEBa3oC6EDRqQPcOsEeB0JB1Pb0wkOywM="
        password: "{cipher}AQBeqjBq5MtOfwEvCzqPq0cZeaZA3Zi0oak/1zLrqIM46BL0hM5p3WvJFSx55fJodnsM1HRd7cSf2xI7xq6x/CnvSP9aNM3PhTzbXhCKEK7FEVSUSbGy07dIUsukwZzP2dnd+Hxjq9ACc20DElDkzCmrF+U91S6K2ef3jBqUoT6gd+66KohryWC6jehbcYvXo75ZI42EkAK7nVcMlNZa+0xNMTRI+TDvybnapJ254v/KnrHkIk2i6PxCaljVb0LMzCJHNLb8W37bpGJlo9ulCDcy5zG70LS0ND6uumPJdIvzprH0tZfQ0onIPW0eraE6ne2mub/21MMKXKx+Ai94zKuwtlm8+urkwXLhtpZbgIaM9aAXnRudnEH9Rb0GY5QtobM="
        druid:
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true