feign:
    httpclient:
        enabled: true
    hystrix:
        enabled: true

hystrix:
    threadpool:
        default:
            coreSize: 200
            maxQueueSize: 1000
            queueSizeRejectionThreshold: 800
    command:
        default:
            execution:
                timeout:
                    enabled: true
                isolation:
                    thread:
                        timeoutInMilliseconds: 120000

ribbon:
    ReadTimeout: 120000
    ConnectTimeout: 5000
spring:
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    data:
        mongodb:
            #uri: mongodb://172.18.102.113:27017/hgny
            uri: mongodb://mongo:Hgny0430@172.22.1.6:27017/hgny?replicaSet=foobar&authSource=admin