eureka:
    instance:
        preferIpAddress: true
        metadataMap:
            group: eeyes-schedule-group
            version: 1.0

spring:
    redis:
        database: 0
        host: 172.22.2.249
        port: 6379
        password: 
        timeout: 6000ms
        jedis:
            pool:
                max-active: 1000
                max-wait: -1ms
                max-idle: 100
                min-idle: 50
    application:
        config:
            path: classpath:rule.xml
    cloud:
        inetutils:
            preferredNetworks: "10.10.0"
        gateway:
            discovery:
                locator:
                    enabled: false
                    lowerCaseServiceId: true
            routes:
            - id: eeyes-ticket
              uri: lb://EEYES-TICKET
              predicates:
              - Path=/eeyes-ticket/**
              filters:
              - StripPrefix=1
              - name: Retry
                args:
                    retries: 5
                    series:
                    - SERVER_ERROR
                    - CLIENT_ERROR
                    statuses:
                    - NOT_FOUND
                    - REQUEST_TIMEOUT
                    - SERVICE_UNAVAILABLE
                    - GATEWAY_TIMEOUT
            - id: eeyescloud-back
              uri: lb://EEYESCLOUD-BACK
              predicates:
              - Path=/eeyescloud-back/**
              filters:
              - StripPrefix=1
              - name: Retry
                args:
                    retries: 5
                    series:
                    - SERVER_ERROR
                    - CLIENT_ERROR
                    statuses:
                    - NOT_FOUND
                    - REQUEST_TIMEOUT
                    - SERVICE_UNAVAILABLE
                    - GATEWAY_TIMEOUT
            - id: eeyes-redis
              uri: lb://EEYES-REDIS
              predicates:
              - Path=/eeyes-redis/**
              filters:
              - StripPrefix=1
              - name: Retry
                args:
                    retries: 5
                    series:
                    - SERVER_ERROR
                    - CLIENT_ERROR
                    statuses:
                    - NOT_FOUND
                    - REQUEST_TIMEOUT
                    - SERVICE_UNAVAILABLE
                    - GATEWAY_TIMEOUT
              - name: RequestRateLimiter
                args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 1
                    key-resolver: "#{@ipKeyResolver}"
            - id: eeyes-api
              uri: lb://EEYES-API
              predicates:
              - Path=/eeyes-api/**
              filters:
              - StripPrefix=1
              - name: Retry
                args:
                    retries: 5
                    series:
                    - SERVER_ERROR
                    - CLIENT_ERROR
                    statuses:
                    - NOT_FOUND
                    - REQUEST_TIMEOUT
                    - SERVICE_UNAVAILABLE
                    - GATEWAY_TIMEOUT
            - id: eeyes-schedule
              uri: lb://EEYES-SCHEDULE
              predicates:
              - Path=/eeyes-schedule/**
              filters:
              - StripPrefix=1
              - name: Retry
                args:
                    retries: 5
                    series:
                    - SERVER_ERROR
                    - CLIENT_ERROR
                    statuses:
                    - NOT_FOUND
                    - REQUEST_TIMEOUT
                    - SERVICE_UNAVAILABLE
                    - GATEWAY_TIMEOUT
            - id: eureka-dfs
              uri: lb://EUREKA-DFS
              predicates:
              - Path=/eureka-dfs/**
              filters:
              - StripPrefix=1
              - name: Retry
                args:
                    retries: 5
                    series:
                    - SERVER_ERROR
                    - CLIENT_ERROR
                    statuses:
                    - NOT_FOUND
                    - REQUEST_TIMEOUT
                    - SERVICE_UNAVAILABLE
                    - GATEWAY_TIMEOUT
            - id: eureka-auth
              uri: lb://EUREKA-AUTH
              predicates:
              - Path=/eureka-auth/**
              filters:
              - StripPrefix=1
              - name: Retry
                args:
                    retries: 5
                    series:
                    - SERVER_ERROR
                    - CLIENT_ERROR
                    statuses:
                    - NOT_FOUND
                    - REQUEST_TIMEOUT
                    - SERVICE_UNAVAILABLE
                    - GATEWAY_TIMEOUT
            - id: python-sidecar
              uri: lb://PYTHON-SIDECAR
              predicates:
              - Path=/python-sidecar/**
              filters:
              - StripPrefix=1
              - name: Retry
                args:
                    retries: 5
                    series:
                    - SERVER_ERROR
                    - CLIENT_ERROR
                    statuses:
                    - NOT_FOUND
                    - INTERNAL_SERVER_ERROR

feign:
    hystrix:
        enabled: true

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        shutdown:
            enabled: true
        health:
            show-details: ALWAYS