server:
   port: 8801

eureka:
   client:
      serviceUrl:
         defaultZone: http://eureka-server:8761/eureka/
         
spring:
   application:
      name: eureka-client
   cloud:
      config:
         label: master
         profile: dev
         discovery:
            enabled: true
            serviceId: config-server
        
git:
    test:
        value: test123