feign:
    httpclient:
        enabled: true
    hystrix:
        enabled: true

hystrix:
    threadpool:
        default:
            coreSize: 200
            maxQueueSize: 1000
            queueSizeRejectionThreshold: 800
    command:
        default:
            execution:
                timeout:
                    enabled: true
                isolation:
                    thread:
                        timeoutInMilliseconds: 120000

ribbon:
    ReadTimeout: 120000
    ConnectTimeout: 5000

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: ALWAYS

spring:
    mvc:
        throw-exception-if-no-handler-found: true
    resources:
        add-mappings: false
    zipkin:
        base-url: http://localhost:9411
    data:
        mongodb:
            address: 172.18.102.113:27017
            replica-set: rs0
            database: hgny
            username: 
            password: 
            min-connections-per-host: 10
            max-connections-per-host: 100
            threads-allowed-to-block-for-connection-multiplier: 5
            server-selection-timeout: 30000
            max-wait-time: 120000
            max-connection-idel-time: 0
            max-connection-life-time: 0
            connect-timeout: 10000
            socket-timeout: 0
            socket-keep-alive: false
            ssl-enabled: false
            ssl-invalid-host-name-allowed: false
            always-use-m-beans: false
            heartbeat-socket-timeout: 20000
            heartbeat-connect-timeout: 20000
            min-heartbeat-frequency: 500
            heartbeat-frequency: 10000
            local-threshold: 15
            authentication-database: auth_dev
            