server:
    port: 8788

spring:
    application:
        name: eureka-admin

eureka:
    instance:
        prefer-ip-address: true
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


      
