spring:
    cloud:
        inetutils:
            preferredNetworks: "10.10.0"
        gateway:
            discovery:
                locator:
                    enabled: false
                    lowerCaseServiceId: true
            routes:
            - id: eeyes-api
              uri: lb://EEYES-API
              predicates:
              - Path=/eeyes-api/**
              filters:
              - StripPrefix=1
              - name: Retry
                args:
                    retries: 3
                    series:
                    - SERVER_ERROR
                    - CLIENT_ERROR
                    statuses:
                    - NOT_FOUND
                    - INTERNAL_SERVER_ERROR
            - id: eureka-client
              uri: lb://EUREKA-CLIENT
              predicates:
              - Path=/eureka-client/**
              filters:
              - StripPrefix=1
              - name: Retry
                args:
                    retries: 3
                    series:
                    - SERVER_ERROR
                    - CLIENT_ERROR
                    statuses:
                    - NOT_FOUND
                    - INTERNAL_SERVER_ERROR
            - id: eeyes-schedule
              uri: lb://EEYES-SCHEDULE
              predicates:
              - Path=/eeyes-schedule/**
              filters:
              - StripPrefix=1
              - name: Retry
                args:
                    retries: 3
                    series:
                    - SERVER_ERROR
                    - CLIENT_ERROR
                    statuses:
                    - NOT_FOUND
                    - INTERNAL_SERVER_ERROR

feign:
    hystrix:
        enabled: true

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        shutdown:
            enabled: true
        health:
            show-details: ALWAYS