server:
    port: 8801
      
spring:
    application:
        name: eureka-client
    zipkin:
        base-url: http://localhost:9411

eureka:
    instance:
        prefer-ip-address: true
        
feign:
    hystrix:
        enabled: true

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: ALWAYS
            
git:
    test:
        value: prod