eureka:
    instance:
        preferIpAddress: true
        metadataMap:
            group: eeyes-schedule-group
            version: 1.0

spring:
    application:
        config:
            path: classpath:rule.xml
    cloud:
        inetutils:
            preferredNetworks: "10.10.0"
        gateway:
            discovery:
                locator:
                    enabled: false
                    lowerCaseServiceId: true
            routes:
            - id: eeyes-api
              uri: lb://EEYES-API
              predicates:
              - Path=/eeyes-api/**
              filters:
              - StripPrefix=1
              - name: Retry
                args:
                    retries: 5
                    series:
                    - SERVER_ERROR
                    - CLIENT_ERROR
                    statuses:
                    - NOT_FOUND
                    - REQUEST_TIMEOUT
                    - SERVICE_UNAVAILABLE
                    - GATEWAY_TIMEOUT
            - id: eeyes-schedule
              uri: lb://EEYES-SCHEDULE
              predicates:
              - Path=/eeyes-schedule/**
              filters:
              - StripPrefix=1
              - name: Retry
                args:
                    retries: 5
                    series:
                    - SERVER_ERROR
                    - CLIENT_ERROR
                    statuses:
                    - NOT_FOUND
                    - REQUEST_TIMEOUT
                    - SERVICE_UNAVAILABLE
                    - GATEWAY_TIMEOUT
            - id: eureka-dfs
              uri: lb://EUREKA-DFS
              predicates:
              - Path=/eureka-dfs/**
              filters:
              - StripPrefix=1
              - name: Retry
                args:
                    retries: 5
                    series:
                    - SERVER_ERROR
                    - CLIENT_ERROR
                    statuses:
                    - NOT_FOUND
                    - REQUEST_TIMEOUT
                    - SERVICE_UNAVAILABLE
                    - GATEWAY_TIMEOUT
            - id: eureka-auth
              uri: lb://EUREKA-AUTH
              predicates:
              - Path=/eureka-auth/**
              filters:
              - StripPrefix=1
              - name: Retry
                args:
                    retries: 5
                    series:
                    - SERVER_ERROR
                    - CLIENT_ERROR
                    statuses:
                    - NOT_FOUND
                    - REQUEST_TIMEOUT
                    - SERVICE_UNAVAILABLE
                    - GATEWAY_TIMEOUT
            - id: python-sidecar
              uri: lb://PYTHON-SIDECAR
              predicates:
              - Path=/python-sidecar/**
              filters:
              - StripPrefix=1
              - name: Retry
                args:
                    retries: 5
                    series:
                    - SERVER_ERROR
                    - CLIENT_ERROR
                    statuses:
                    - NOT_FOUND
                    - INTERNAL_SERVER_ERROR

feign:
    hystrix:
        enabled: true

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        shutdown:
            enabled: true
        health:
            show-details: ALWAYS