server:
    port: 8900

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/
            
spring:
    application:
        name: eureka-turbine

management:
    endpoints:
        web:
            exposure:
                include: "*"
        cors:
            allowed-origins: "*"
            allowed-methods: "*"

turbine:
    app-config: eureka-client,eureka-call
    aggregator:
        clusterConfig: default
    clusterNameExpression: new String("default")
    combine-host: true
    instanceUrlSuffix:
        default: actuator/hystrix.stream    
